apiVersion: v1
kind: Secret
metadata:
  name: codearena-secrets
  namespace: codearena
type: Opaque
stringData:
  POSTGRES_USER: "<SET_IN_PROD>"
  POSTGRES_PASSWORD: "<SET_IN_PROD>"
  REDIS_PASSWORD: "<SET_IN_PROD>"
  RABBITMQ_PASSWORD: "<SET_IN_PROD>"
  JWT_SECRET: "<SET_IN_PROD_CHANGE_ME>"
  AWS_ACCESS_KEY_ID: "<SET_IN_PROD>"
  AWS_SECRET_KEY: "<SET_IN_PROD>"
  AWS_REGION: "<SET_IN_PROD>"
  AWS_S3_BUCKET: "<SET_IN_PROD>"
  OPENAI_API_KEY: "<SET_IN_PROD>"
